server:
  port: 8881
# 自定义参数
book:
  name: 微服务实战
  author: none
  desc: ${book.author} is writing 《${book.name}》
management:
  endpoints:
    web:
      exposure:
        include: '*'
---

spring:
  profiles: test
server:
  port: 8882

---

spring:
  profiles: prod
server:
  port: 8883
